/**
 * Typed access to the abolitionist-church list.
 *
 * Source: data/abolitionist-churches.json, which is REGENERATED by
 * scripts/sync-abolitionist-churches.mjs from Dustin's NXR church
 * directory export (Church.json — the abolitionStance='pro_abolition'
 * subset). Don't hand-edit the JSON; re-sync it.
 *
 * Join key with lib/data/cities.ts is city + state — same city name
 * can exist across states (Portland OR vs Portland ME), so both
 * fields are required for a correct match. When the result is empty
 * for a city, the page renders an honest "not aware of any" callout
 * instead of an empty list.
 */

import raw from '@/data/abolitionist-churches.json';

export interface AbolitionistChurch {
  id: string;
  name: string;
  denomination: string;
  address: string;
  city: string;
  state: string | null;
  website: string | null;
  phone: string | null;
  email: string | null;
  pastor: string | null;
  notes: string | null;
}

interface RawData {
  note: string;
  syncedFrom?: string;
  syncedAt?: string;
  totalScanned?: number;
  matched?: number;
  churches: AbolitionistChurch[];
}

const DATA = raw as RawData;

export function getAllChurches(): AbolitionistChurch[] {
  return DATA.churches;
}

export function getChurchesByCity(cityName: string, state?: string): AbolitionistChurch[] {
  const needle = cityName.trim().toLowerCase();
  const stateNeedle = state ? state.trim().toLowerCase() : null;
  return DATA.churches.filter((c) => {
    if (c.city.trim().toLowerCase() !== needle) return false;
    if (stateNeedle && (c.state || '').trim().toLowerCase() !== stateNeedle) return false;
    return true;
  });
}

/** Sync metadata for the page footer ("Directory last synced YYYY-MM-DD"). */
export function getChurchesSyncMeta() {
  return {
    syncedAt: DATA.syncedAt || null,
    matched: DATA.matched ?? DATA.churches.length,
    totalScanned: DATA.totalScanned ?? null,
  };
}
